"use client";
import Link from "next/link";
import { useCallback,useEffect,useState } from "react";
import { authFetch } from "@/utils/api/auth-fetch";
interface EventRow{id:string;title:string;type:string}
interface Setting{event_id:string;category:string;hidden_coefficient?:number}
const categories=[["training","Тренировка"],["amateur","Любительский"],["regional","Региональный"],["official","Официальный"],["season_final","Финал сезона"]] as const;
export default function RatingSettingsPage(){
 const [events,setEvents]=useState<EventRow[]>([]);const [settings,setSettings]=useState<Setting[]>([]);const [isOwner,setIsOwner]=useState(false);const [message,setMessage]=useState("");
 const load=useCallback(async()=>{const response=await authFetch("/api/admin/rating-settings");const payload=await response.json();if(response.ok){setEvents(payload.events??[]);setSettings(payload.settings??[]);setIsOwner(Boolean(payload.isOwner));}else setMessage(payload.error??"Ошибка");},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
 const save=async(eventId:string,category:string,coefficient?:number)=>{const response=await authFetch("/api/admin/rating-settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({eventId,category,coefficient})});const payload=await response.json();setMessage(response.ok?"Категория сохранена":payload.error??"Ошибка");if(response.ok)await load();};
 return <div className="page-shell"><span className="section-kicker">СКРЫТЫЕ НАСТРОЙКИ</span><h1 className="mb-2 mt-2 text-3xl font-black">Категории рейтинговых мероприятий</h1><p className="mb-6 text-sm text-slate-400">{isOwner?"Вы видите служебные коэффициенты как владелец.":"Числовые коэффициенты доступны только владельцу."}</p>{message&&<p className="mb-4 rounded-xl bg-white/[.05] p-3">{message}</p>}<div className="space-y-3">{events.map(event=>{const current=settings.find(s=>s.event_id===event.id);return <article key={event.id} className="cyber-card grid items-end gap-3 p-4 md:grid-cols-[1fr_220px_160px_auto]"><div><strong>{event.title}</strong><p className="text-xs text-slate-500">{event.type}</p></div><label className="text-xs text-slate-400">Категория<select defaultValue={current?.category??(event.type==="training"?"training":"amateur")} id={"category-"+event.id}>{categories.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{isOwner?<label className="text-xs text-slate-400">Скрытый коэффициент<input id={"coefficient-"+event.id} type="number" min=".01" max="5" step=".01" defaultValue={current?.hidden_coefficient??1}/></label>:<span className="text-sm text-slate-500">Коэффициент скрыт</span>}<button className="secondary-button" onClick={()=>{const category=(document.getElementById("category-"+event.id) as HTMLSelectElement).value;const input=document.getElementById("coefficient-"+event.id) as HTMLInputElement|null;void save(event.id,category,input?Number(input.value):undefined);}}>Сохранить</button></article>})}</div><Link href="/admin" className="mt-6 inline-flex text-cyan-300">← Админ-панель</Link></div>;
}
