import assert from 'node:assert/strict';
export async function verifyDuels(db,id){
 await db.query(`insert into public.team_members(team_id,user_id,role_in_team) values($1,$2,'leader'),($3,$4,'leader') on conflict(team_id,user_id) do update set role_in_team='leader'`,[id(110),id(2),id(111),id(3)]);
 await db.query(`insert into public.clan_wars(id,creator_team_id,opponent_team_id,created_by,title,status) values($1,$2,$3,$4,'Consent test','agreed')`,[id(400),id(110),id(111),id(2)]);
 await db.query(`insert into public.clan_war_rosters(clan_war_id,team_id,player_ids,submitted_by) values($1,$2,array[$3::uuid],$3),($1,$4,array[$5::uuid],$5)`,[id(400),id(110),id(2),id(111),id(3)]);
 const game=(await db.query(`select id,public_number from public.clan_war_games where clan_war_id=$1`,[id(400)])).rows[0];
 const document=(aWins=true)=>({rules:{mode:'kv'},mvps:[id(aWins?2:3)],rows:[0,1].map(i=>({registrationId:id(110+i),teamId:id(110+i),userId:null,groupId:id(400),gameId:game.id,played:true,rounds:(i===0)===aWins?7:2,place:(i===0)===aWins?1:2,kills:i?2:8,reason:'no_show',detail:'players',points:0,fieldSize:2,name:`Team ${i}`,
 players:[{id:id(i+2),userId:id(i+2),played:true,nickname:`Player ${i}`,kills:i?2:8,deaths:i?8:2,assists:i?0:4}]})),standings:[0,1].map(i=>({teamId:id(110+i),registrationId:id(110+i),groupId:id(400),name:`Team ${i}`,wins:(i===0)===aWins?1:0,kills:i?2:8,place:(i===0)===aWins?1:2,gamesPlayed:1}))});
 let request=500;
 const action=async(actor,kind,revision,doc=null,team=null,req=++request)=>(await db.query(`select public.u2_war_results($1,$2,$3,$4,2,$5,$6,$7::jsonb,$8::jsonb,$9) value`,[id(actor),id(400),kind,revision,id(req),JSON.stringify({kind,revision,doc,team}),doc?JSON.stringify({rows:doc.rows,warnings:[],manualOrder:[]}):null,doc?JSON.stringify(doc):null,team?id(team):null])).rows[0].value;
 await db.query(`insert into public.betting_markets(id,mode,clan_war_id,subject_team_id,market_type) values($1,'kv',$2,$3,'win')`,[id(401),id(400),id(110)]);
 await db.query(`insert into public.site_bets(id,user_id,market_id,stake,odds,potential_payout) values($1,$2,$3,10,2,20)`,[id(402),id(2),id(401)]);
 await action(2,'publish',0,document());
 assert.equal((await db.query(`select count(*)::int n from public.competition_duels`)).rows[0].n,0);
 assert.equal((await action(2,'approve',1,null,110)).published,false);
 await assert.rejects(()=>action(2,'approve',1,null,111),/Нет прав/);
 await assert.rejects(()=>action(1,'approve',1,null,111),/Нет прав/,'An unrelated administrator must use an explicit resolution, not consent for a team');
 const confirmed=await action(3,'approve',1,null,111,550);assert.equal(confirmed.published,true);
 assert.deepEqual(await action(3,'approve',1,null,111,550),confirmed);
 const rating=async(team)=>(await db.query(`select * from public.competition_ratings where target_type='team' and target_id=$1 and mode='kv'`,[id(team)])).rows[0];
 assert.ok(Math.abs(Number((await rating(110)).exact_rating)-55.6)<1e-10);
 const personal=(await db.query(`select * from public.competition_ratings where target_type='player' and target_id=$1 and mode='kv'`,[id(2)])).rows[0];
 assert.equal(personal.games,1);assert.equal(personal.series,1);assert.ok(Math.abs(Number(personal.exact_rating)-52.839)<1e-10);
 assert.equal((await db.query(`select payout from public.site_bets where id=$1`,[id(402)])).rows[0].payout,20);
 await assert.rejects(()=>db.query(`update public.clan_war_rosters set player_ids='{}' where clan_war_id=$1`,[id(400)]),/Нельзя менять состав/);
 await action(2,'publish',1,document(false));
 assert.equal(Number((await rating(110)).exact_rating),55.6);
 assert.equal((await db.query(`select payout from public.site_bets where id=$1`,[id(402)])).rows[0].payout,20);
 await assert.rejects(()=>action(3,'approve',1,null,111),/Конфликт версии/);
 await action(2,'approve',2,null,110);await action(3,'dispute',2,null,111);
 await assert.rejects(()=>action(2,'approve',2,null,110),/Спор рассматривает/);
 await assert.rejects(()=>action(2,'resolve',2),/Требуются права/);
 await action(1,'resolve',2);
 assert.equal(Number((await rating(110)).exact_rating),44.4);
 assert.equal((await db.query(`select payout from public.site_bets where id=$1`,[id(402)])).rows[0].payout,0);
 const later=structuredClone(document());later.rows.forEach(r=>r.groupId=id(600));
 await db.query(`select public.u2_sync_duels($1::jsonb,now()+interval '1 day')`,[JSON.stringify(later)]);
 const before=(await db.query(`select opponent_a_before from public.competition_duels where id=$1`,[id(600)])).rows[0].opponent_a_before;
 await action(2,'publish',2,document());await action(1,'resolve',3);
 const after=(await db.query(`select opponent_a_before from public.competition_duels where id=$1`,[id(600)])).rows[0].opponent_a_before;
 assert.equal(Number(before),44.4);assert.equal(Number(after),55.6);assert.equal((await rating(110)).series,2);
 const bo=structuredClone(document());bo.rules.mode='bo';bo.rows.forEach(r=>r.groupId=id(601));
 await db.query(`select public.u2_sync_duels($1::jsonb,now())`,[JSON.stringify(bo)]);
 assert.equal((await rating(110)).series,2);
 assert.equal((await db.query(`select series from public.competition_ratings where target_id=$1 and target_type='team' and mode='bo'`,[id(110)])).rows[0].series,1);
 assert.equal((await db.query(`select public_number from public.clan_war_games where id=$1`,[game.id])).rows[0].public_number,game.public_number);
 const disabled=structuredClone(bo);disabled.rules.ratingEnabled=false;disabled.rows.forEach(r=>r.groupId=id(602));
 const beforeDisabled=(await db.query(`select exact_rating from competition_ratings where target_type='team' and target_id=$1 and mode='bo'`,[id(110)])).rows[0].exact_rating;
 await db.query(`select u2_sync_duels($1::jsonb,now()+interval '1 day')`,[JSON.stringify(disabled)]);
 assert.equal((await db.query(`select exact_rating from competition_ratings where target_type='team' and target_id=$1 and mode='bo'`,[id(110)])).rows[0].exact_rating,beforeDisabled);
 assert.equal((await db.query(`select series from competition_duel_totals where target_type='team' and target_id=$1 and mode='bo'`,[id(110)])).rows[0].series,2,'Rating-disabled series remains in sporting statistics');
 console.log('PASS: both-side current-revision KV consent, disputes, admin decision, stale consent, payout preservation/reversal, roster snapshot, independent BO/KV and chronological replay');
}
