import assert from 'node:assert/strict';
export async function verifyRegistrations(db,id,base){
 const config=structuredClone(base);config.cost=0;
 const source={...structuredClone(base.sessions[0]),id:id(700),sourceSessionId:null,stage:'qualification',groups:[{id:id(701),name:'Source',capacity:12,games:[{id:id(702),map:'bermuda'}]}]};
 const next={...structuredClone(source),id:id(710),stage:'final',sourceSessionId:id(700),startTime:new Date(Date.now()+172800000).toISOString(),endTime:new Date(Date.now()+176400000).toISOString(),qualification:{mode:'general',count:1,transfer:'percent',value:50},groups:[{id:id(711),name:'Final',capacity:12,games:[{id:id(712),map:'kalahari'}]}]};
 config.sessions=[next,source];config.finalSessionId=next.id;
 const event=(await db.query(`select public.u2_event_configuration($1,null,0,$2::jsonb) value`,[id(1),JSON.stringify(config)])).rows[0].value.eventId;
 let request=800;
 const revision=async(session)=>(await db.query(`select configuration_revision from public.event_sessions where id=$1`,[session])).rows[0].configuration_revision;
 const manage=async(session,change,actor=1)=>(await db.query(`select public.u2_registration_action($1,$2,$3,$4::jsonb,$5) value`,[id(actor),session,await revision(session),JSON.stringify(change),id(++request)])).rows[0].value;
 await manage(source.id,{action:'add',targetType:'team',targetId:id(110),roster:[id(2)],groupId:id(701),status:'confirmed'});
 await manage(source.id,{action:'add',targetType:'team',targetId:id(111),roster:[id(3)],groupId:id(701),status:'confirmed'});
 await assert.rejects(()=>manage(source.id,{action:'distribute',mode:'balanced'},3),/Распределение подтверждает/);
 await manage(source.id,{action:'distribute',mode:'balanced'});
 const regs=(await db.query(`select * from public.event_registrations where session_id=$1 order by team_id`,[source.id])).rows;
 const originalName=regs[0].roster_snapshot[0].nickname;
 await db.query(`update public.profiles set nickname='Renamed after registration' where id=$1`,[id(2)]);
 assert.equal((await db.query(`select roster_snapshot from public.event_registrations where id=$1`,[regs[0].id])).rows[0].roster_snapshot[0].nickname,originalName);
 const doc=(kills=10)=>({rules:config.rules,mvps:[],rows:regs.map((r,i)=>({registrationId:r.id,gameId:id(702),groupId:id(701),teamId:r.team_id,userId:null,name:r.name_snapshot,played:true,place:i+1,kills:i?1:kills,points:i?10:12+kills,rounds:null,detail:'team',players:[],reason:'no_show',fieldSize:2})),standings:regs.map((r,i)=>({registrationId:r.id,groupId:id(701),teamId:r.team_id,userId:null,name:r.name_snapshot,place:i+1,kills:i?1:kills,points:i?10:12+kills,gamesPlayed:1,wins:i?0:1,placeSum:i+1,bonus:0,manual:false}))});
 const publish=async(document,rev,removed=[])=>db.query(`select public.u2_save_results($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9,'[]',$10::uuid[]) value`,[id(1),source.id,rev,await revision(source.id),id(++request),`case-${request}`,JSON.stringify({rows:document.rows,warnings:[],manualOrder:[]}),JSON.stringify(document),removed.length>0,removed]);
 await publish(doc(),0);
 await assert.rejects(()=>db.query(`update public.event_registrations set status='cancelled' where id=$1`,[regs[1].id]),/опубликованной заявки/);
 await assert.rejects(()=>manage(source.id,{action:'remove',id:regs[1].id}),/опубликованной заявки/);
 const qualify=(rev)=>manage(next.id,{action:'qualify',sourceRevision:rev,selectedIds:[regs[0].id]});
 await assert.rejects(()=>qualify(0),/Конфликт версии квалификации/);
 await qualify(1);
 let passed=(await db.query(`select * from public.event_registrations where session_id=$1 and status='confirmed'`,[next.id])).rows;
 assert.equal(passed[0].roster_snapshot[0].nickname,originalName);
 assert.equal(passed.length,1);assert.equal(passed[0].qualification_source_id,regs[0].id);assert.equal(Number(passed[0].carried_points),11);
 await publish(doc(8),1);await qualify(2);await qualify(2);
 passed=(await db.query(`select * from public.event_registrations where session_id=$1 and status='confirmed'`,[next.id])).rows;
 assert.equal(passed.length,1);assert.equal(Number(passed[0].carried_points),10);
 await db.query(`update public.event_sessions set start_time=now()-interval '1 hour' where id=$1`,[next.id]);
 await publish(doc(20),2);
 assert.equal(Number((await db.query(`select carried_points from public.event_registrations where id=$1`,[passed[0].id])).rows[0].carried_points),10);
 await assert.rejects(()=>manage(next.id,{action:'qualify',sourceRevision:3,selectedIds:[],confirmStarted:true}),/уже начался/);
 const fewer=doc(20);fewer.rows=fewer.rows.slice(0,1);fewer.standings=fewer.standings.slice(0,1);
 await publish(fewer,3,[regs[1].id]);
 assert.equal((await db.query(`select status from public.event_registrations where id=$1`,[regs[1].id])).rows[0].status,'cancelled');
 assert.equal((await db.query(`select count(*)::int n from public.competition_team_facts where session_id=$1`,[source.id])).rows[0].n,1);
 assert.equal((await db.query(`select result_status from public.organization_participation_history where session_id=$1 and organization_id=$2`,[source.id,id(111)])).rows[0].result_status,'cancelled');
 assert.equal((await db.query(`select event_id from public.event_sessions where id=$1`,[next.id])).rows[0].event_id,event);
 console.log('PASS: registration manager permissions, snapshots, published mutation guard, atomic admin removal, deferred stage references, qualification correction/transfer without duplication and started-stage freeze');
}
