"use client";
import Link from "next/link";
import {useLanguage} from "./LanguageProvider";
import {competitionText} from "@/i18n/competition";
import type {Game,GameResult,Standing} from "@/lib/competition/model";
export default function CompetitionTable({standings,rows,games,mode,criterion}:{standings:Standing[];rows?:GameResult[];games?:Game[];mode?:string;criterion?:string}){
 const {locale}=useLanguage();const t=(key:Parameters<typeof competitionText>[1])=>competitionText(locale,key);
 const round=mode==="bo"||mode==="kv";
 return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{[t("place"),t("target"),t("games"),t("wins"),t("kills"),...(!round?[criterion==="places"?t("place"):t("points")]:[])].map((s,i)=><th key={i} className="p-2">{s}</th>)}</tr></thead><tbody>{standings.map(row=><tr key={row.registrationId} className="border-t border-white/10"><td className="p-2">{row.place}</td><td className="p-2"><Link href={row.teamId?`/teams/${row.teamId}`:`/profile/${row.userId}`} className="text-cyan-300">{row.name}</Link>{rows&&<details className="mt-2"><summary className="cursor-pointer text-xs text-white/60">{t("detail")}</summary><div className="space-y-2 py-2">{rows.filter(r=>r.registrationId===row.registrationId).sort((a,b)=>(games?.find(g=>g.id===a.gameId)?.number??0)-(games?.find(g=>g.id===b.gameId)?.number??0)).map(r=>{const game=games?.find(g=>g.id===r.gameId);return <div key={r.gameId} className="rounded-lg border border-white/10 p-2"><p className="font-bold">{t("game")} {game?.number} · {game?.publicId} · {game?.map}</p><p>{!r.played?t("notPlayed"):`${t(round?"rounds":"place")}: ${round?r.rounds??"—":r.place} · ${t("kills")}: ${r.kills}`}</p>{r.played&&r.detail==="team"?<p className="text-white/50">{t("teamOnly")}</p>:r.players.map(p=><p key={p.id} className={!p.played?"text-white/40":"text-white/75"}>{p.userId?<Link href={`/profile/${p.userId}`}>{p.nickname}</Link>:t("guest")}: {p.played?`${t("kills")}: ${p.kills}${round?` · ${t("deaths")}: ${p.deaths} · ${t("assists")}: ${p.assists} · KDA: ${(((p.kills??0)+(p.assists??0))/Math.max(1,p.deaths??0)).toFixed(2)}`:""}`:t("notPlayed")}</p>)}</div>;})}</div></details>}</td><td className="p-2">{row.gamesPlayed}</td><td className="p-2">{row.wins}</td><td className="p-2">{row.kills}</td>{!round&&<td className="p-2">{criterion==="places"?row.placeSum:row.points}{!!row.bonus&&<small className="block text-white/40">+{row.bonus}</small>}</td>}</tr>)}</tbody></table></div>;
}
