"use client";
import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {authFetch} from "@/utils/api/auth-fetch";
import {useLanguage} from "./LanguageProvider";
import {competitionText} from "@/i18n/competition";
type SourceType="warning"|"sanction"|"blacklist";
interface Warning{id:string;target_type:"player"|"team";target_id:string;reason:string;penalty:number;expires_at:string|null;status:"active"|"expired"|"cancelled"|"used";canCancel:boolean;canAppeal:boolean;organizer_id:string|null;event_id:string|null;cancellation_reason?:string}
interface Sanction{id:string;target_type:"player"|"team";target_id:string;organizer_id:string|null;reason:string;ends_at:string|null;lifted_at:string|null;scopes:string[]}
interface Blacklist{id:string;target_type:"player"|"team";target_id:string;organizer_id:string;event_id:string|null;reason:string|null;expires_at:string|null;removed_at:string|null}
interface Appeal{id:string;source_type:SourceType;source_id:string;applicant_id:string;recipient_id:string;message:string;evidence:string[];status:"pending"|"approved"|"rejected";answer:string|null}
interface Data{generatedAt:number;prefillTargetType?:string;prefillTargetId?:string;actor:string;isAdmin:boolean;isModerator:boolean;isOwner:boolean;warnings:Warning[];sanctions:Sanction[];blacklist:Blacklist[];appeals:Appeal[];applications:Array<{user_id:string;status:string;message:string}>;profiles:Array<{id:string;nickname:string}>;events:Array<{id:string;title:string}>;teamIds:string[];recipientIds:string[];adminIds:string[];source:{id:string;type:SourceType;reason:string;organizer_id:string|null}|null}
export default function CompetitionModeration({initialTab="appeals"}:{initialTab?:"appeals"|"warnings"|"blacklist"|"organizer"}){
 const {locale}=useLanguage();const t=(key:Parameters<typeof competitionText>[1])=>competitionText(locale,key);const tr=(ru:string,kk:string,ky:string)=>locale==="kk"?kk:locale==="ky"?ky:ru;
 const [data,setData]=useState<Data|null>(null),[tab,setTab]=useState(initialTab),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[sourceValue,setSourceValue]=useState(""),[cancelId,setCancelId]=useState(""),[cancelReason,setCancelReason]=useState("");
 const load=useCallback(async()=>{try{const query=new URLSearchParams(window.location.search),r=await authFetch(`/api/competition/moderation${query.has("sourceId")?`?sourceId=${encodeURIComponent(query.get("sourceId")!)}&sourceType=${encodeURIComponent(query.get("sourceType")??"")}`:""}`),d=await r.json();if(!r.ok)throw new Error(d.error);setData({...d,prefillTargetType:query.get("targetType"),prefillTargetId:query.get("targetId")});if(d.source)setSourceValue(`${d.source.type}:${d.source.id}`);}catch(e){setMessage(e instanceof Error?e.message:"Ошибка загрузки");}},[]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
 const act=async(payload:Record<string,unknown>)=>{setBusy(true);setMessage("");try{const r=await authFetch("/api/competition/moderation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw new Error(d.error);await load();setMessage(tr("Изменения сохранены","Өзгерістер сақталды","Өзгөртүүлөр сакталды"));return true;}catch(e){setMessage(e instanceof Error?e.message:t("failed"));return false;}finally{setBusy(false);}};
 if(!data)return <main className="page-shell"><p role="status">{message||t("loading")}</p></main>;
 const name=(id:string)=>data.profiles.find(p=>p.id===id)?.nickname??id;
 const target=(kind:string,id:string)=><Link className="text-cyan-300 break-all" href={kind==="player"?`/profile/${id}`:`/teams/${id}`}>{name(id)}</Link>;
 const canAppeal=(id:string)=>id===data.actor||data.teamIds.includes(id);
 const sources=[...data.warnings.filter(w=>w.canAppeal).map(w=>({id:w.id,type:"warning" as const,reason:w.reason,organizer_id:w.organizer_id})),...data.sanctions.filter(s=>canAppeal(s.target_id)).map(s=>({id:s.id,type:"sanction" as const,reason:s.reason,organizer_id:s.organizer_id})),...(data.source?[data.source]:[])].filter((source,index,array)=>array.findIndex(s=>s.type===source.type&&s.id===source.id)===index);
 const source=sources.find(s=>`${s.type}:${s.id}`===sourceValue),recipients=[...new Set([...data.adminIds,...(source?.organizer_id?[source.organizer_id]:[])])];
 const inputClass="w-full rounded-lg border border-white/20 bg-slate-950 p-2";
 return <main className="page-shell space-y-5"><h1 className="text-3xl font-black">{t(tab)}</h1><nav className="flex flex-wrap gap-3">{(["appeals","warnings","blacklist","organizer"] as const).map(key=><button key={key} className={tab===key?"primary-button":"secondary-button"} onClick={()=>setTab(key)}>{t(key)}</button>)}</nav>{message&&<p role="status" className="rounded-xl border border-white/20 p-3">{message}</p>}
 {tab==="appeals"&&<><form className="cyber-card space-y-3 p-5" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(!source)return;await act({action:"appeal",sourceType:source.type,sourceId:source.id,recipientId:f.get("recipient"),message:f.get("message"),evidence:String(f.get("evidence")??"").split(/\r?\n/).map(s=>s.trim()).filter(Boolean)});}}><h2 className="text-xl font-bold">{tr("Новое обжалование","Жаңа шағым","Жаңы даттануу")}</h2><label className="block">{tr("Решение","Шешім","Чечим")}<select className={inputClass} required value={sourceValue} onChange={e=>setSourceValue(e.target.value)}><option value="">{t("choose")}</option>{sources.map(s=><option key={`${s.type}:${s.id}`} value={`${s.type}:${s.id}`}>{s.reason} · {s.id.slice(0,8)}</option>)}</select></label><label className="block">{t("target")}<select className={inputClass} name="recipient" required defaultValue=""><option value="">{t("choose")}</option>{recipients.map(id=><option key={id} value={id}>{name(id)} · {data.adminIds.includes(id)?tr("Администрация","Әкімшілік","Администрация"):t("organizer")}</option>)}</select></label><label className="block">{tr("Обращение","Өтініш","Кайрылуу")}<textarea className={inputClass} name="message" required minLength={1} maxLength={10000}/></label><label className="block">{tr("Ссылки на доказательства, каждая с новой строки","Дәлел сілтемелері, әрқайсысы жаңа жолда","Далил шилтемелери, ар бири жаңы сапта")}<textarea className={inputClass} name="evidence" placeholder="https://…"/></label><p className="text-sm text-white/50">{tr("Одно обращение на решение. Ограничение действует до отдельной отмены.","Бір шешімге бір өтініш. Шектеу жеке жойылғанға дейін әрекет етеді.","Бир чечимге бир кайрылуу. Чектөө өзүнчө жокко чыгарылганга чейин күчүндө.")}</p><button disabled={busy||!source||data.appeals.some(a=>a.source_type===source.type&&a.source_id===source.id)} className="primary-button">{t("send")}</button></form>
 <div className="space-y-3">{!data.appeals.length&&<p>{t("empty")}</p>}{data.appeals.map(a=><article key={a.id} className="cyber-card space-y-3 p-5"><div className="flex flex-wrap justify-between"><p>{name(a.applicant_id)} → {name(a.recipient_id)}</p><span>{t(a.status==="pending"?"pending":a.status==="approved"?"approve":"reject")}</span></div><p className="whitespace-pre-wrap">{a.message}</p>{a.evidence.map((url,i)=><a key={i} className="block break-all text-cyan-300" href={url} rel="noreferrer" target="_blank">{t("evidence")} {i+1}</a>)}{a.answer&&<p className="border-t border-white/10 pt-3 whitespace-pre-wrap">{t("answer")}: {a.answer}</p>}{a.status==="pending"&&(data.isAdmin||a.recipient_id===data.actor)&&<form className="space-y-3 border-t border-white/10 pt-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act({action:"decide_appeal",id:a.id,approve:f.get("approve")==="on",answer:f.get("answer"),cancelWarning:f.get("cancelWarning")==="on",liftSanction:f.get("liftSanction")==="on"});}}><textarea aria-label={t("answer")} required maxLength={10000} name="answer" className={inputClass}/><label className="block"><input type="checkbox" name="approve"/> {t("approve")}</label>{a.source_type==="warning"&&<label className="block"><input type="checkbox" name="cancelWarning"/> {tr("Отменить предупреждение","Ескертуді жою","Эскертүүнү жокко чыгаруу")}</label>}{a.source_type!=="blacklist"&&<label className="block"><input type="checkbox" name="liftSanction"/> {tr("Отдельно снять связанное отстранение","Байланысты шеттетуді бөлек алып тастау","Байланыштуу четтетүүнү өзүнчө алып салуу")}</label>}<button className="primary-button" disabled={busy}>{t("send")}</button></form>}</article>)}</div></>}
 {tab==="warnings"&&<><div className="space-y-3">{data.warnings.map(w=><article key={w.id} className={`cyber-card space-y-2 p-4 ${w.status==="active"?w.expires_at?"text-orange-200":"text-red-300":"text-white/40"}`}><p>{target(w.target_type,w.target_id)} · {t(w.status)} · −{w.penalty}</p><p>{w.reason}</p>{w.event_id&&<Link className="text-cyan-300" href={`/tournaments/${w.event_id}`}>{tr("Мероприятие","Іс-шара","Иш-чара")}</Link>}{w.cancellation_reason&&<p>{tr("Причина отмены","Жою себебі","Жокко чыгаруу себеби")}: {w.cancellation_reason}</p>}<div className="flex flex-wrap gap-3">{w.canCancel&&<button disabled={busy} className="secondary-button" onClick={()=>{setCancelId(w.id);setCancelReason("");}}>{t("cancel")}</button>}{w.canAppeal&&<button className="secondary-button" onClick={()=>{setSourceValue(`warning:${w.id}`);setTab("appeals");}}>{t("appeals")}</button>}</div>{cancelId===w.id&&<form className="flex flex-wrap gap-3" onSubmit={async e=>{e.preventDefault();if(await act({action:"cancel_warning",id:w.id,reason:cancelReason}))setCancelId("");}}><input className={inputClass} required maxLength={1000} aria-label={t("reason")} placeholder={t("reason")} value={cancelReason} onChange={e=>setCancelReason(e.target.value)}/><button className="primary-button" disabled={busy}>{tr("Отменить предупреждение","Ескертуді жою","Эскертүүнү жокко чыгаруу")}</button></form>}</article>)}</div>
 <h2 className="text-xl font-bold">{tr("Отстранения","Шеттетулер","Четтетүүлөр")}</h2>{data.sanctions.map(s=><article key={s.id} className="cyber-card space-y-2 p-4"><p>{target(s.target_type,s.target_id)} · {s.reason}</p><p>{s.scopes.join(" · ")} · {s.lifted_at?t("cancelled"):s.ends_at?new Date(s.ends_at).toLocaleString("ru-RU",{timeZone:"Europe/Moscow"})+" МСК":t("permanent")}</p>{!s.lifted_at&&(data.isAdmin||s.organizer_id===data.actor)&&<button className="secondary-button" disabled={busy} onClick={()=>void act({action:"lift_sanction",id:s.id})}>{tr("Снять отстранение","Шеттетуді алып тастау","Четтетүүнү алып салуу")}</button>}{canAppeal(s.target_id)&&<button className="secondary-button ml-3" onClick={()=>{setSourceValue(`sanction:${s.id}`);setTab("appeals");}}>{t("appeals")}</button>}</article>)}
 {(data.isAdmin||data.isModerator)&&<form className="cyber-card grid gap-3 p-5 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act({action:"issue_warning",sessionId:String(f.get("sessionId"))||null,warning:{id:crypto.randomUUID(),targetType:f.get("targetType"),targetId:f.get("targetId"),gameId:null,source:"manual",reason:f.get("reason"),category:f.get("category"),duration:f.get("duration"),penalty:Number(f.get("penalty"))}});}}><h2 className="text-xl font-bold sm:col-span-2">{t("addWarning")}</h2><select aria-label={t("target")} className={inputClass} name="targetType" defaultValue={data.prefillTargetType??"player"}><option value="player">{t("player")}</option><option value="team">{t("team")}</option></select><input className={inputClass} name="targetId" required defaultValue={data.prefillTargetId??""} placeholder="UUID" aria-label="ID"/><input className={inputClass} name="sessionId" placeholder={`${t("session")} UUID`} aria-label={`${t("session")} ID`}/><select className={inputClass} name="category" defaultValue={data.isAdmin?"event":"chat"} aria-label={t("warning")}><option disabled={!data.isAdmin} value="event">{tr("Мероприятия","Іс-шаралар","Иш-чаралар")}</option><option value="chat">{tr("Чат","Чат","Чат")}</option></select><textarea className={inputClass} name="reason" required maxLength={1000} placeholder={t("reason")}/><label>{t("penalty")}<input className={inputClass} name="penalty" type="number" min={1} max={99} required/></label><select required defaultValue="" className={inputClass} name="duration" aria-label={t("warning")}><option value="">{t("choose")}</option><option value="week">{t("week")}</option><option value="permanent">{t("permanent")}</option></select><button disabled={busy} className="primary-button">{t("send")}</button></form>}</>}
 {tab==="blacklist"&&<><form className="cyber-card grid gap-3 p-5 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),expiry=String(f.get("expiry")??"");void act({action:"blacklist_add",organizerId:String(f.get("organizerId")??"")||null,targetType:f.get("targetType"),targetId:f.get("targetId"),eventId:String(f.get("eventId"))||null,reason:f.get("reason"),expiresAt:expiry?new Date(`${expiry}:00+03:00`).toISOString():null});}}><h2 className="text-xl font-bold sm:col-span-2">{t("blacklist")}</h2><select className={inputClass} aria-label={t("target")} name="targetType"><option value="player">{t("player")}</option><option value="team">{t("team")}</option></select><input className={inputClass} name="targetId" required defaultValue={data.prefillTargetId??""} placeholder="UUID" aria-label="ID"/>{data.isAdmin&&<input name="organizerId" className={inputClass} placeholder={`${t("organizer")} UUID`} aria-label={t("organizer")}/>}<select className={inputClass} aria-label={tr("Мероприятие","Іс-шара","Иш-чара")} name="eventId"><option value="">{tr("Все мероприятия организатора","Ұйымдастырушының барлық іс-шаралары","Уюштуруучунун бардык иш-чаралары")}</option>{data.events.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select><label>{tr("До (МСК), пусто — бессрочно","Дейін (Мәскеу), бос — мерзімсіз","Чейин (Москва), бош — мөөнөтсүз")}<input className={inputClass} name="expiry" type="datetime-local"/></label><textarea className={inputClass} name="reason" placeholder={t("reason")} maxLength={1000}/><button className="primary-button" disabled={busy}>{t("send")}</button></form>{data.blacklist.map(b=><article className="cyber-card space-y-2 p-4" key={b.id}><p>{target(b.target_type,b.target_id)} · {b.removed_at?t("cancelled"):b.expires_at&&Date.parse(b.expires_at)<=data.generatedAt?t("expired"):t("active")}</p><p>{b.reason}</p>{b.event_id&&<Link className="text-cyan-300" href={`/tournaments/${b.event_id}`}>{tr("Мероприятие","Іс-шара","Иш-чара")}</Link>}{!b.removed_at&&<button disabled={busy} className="secondary-button" onClick={()=>void act({action:"blacklist_remove",id:b.id})}>{t("remove")}</button>}</article>)}</>}
 {tab==="organizer"&&<><Link className="primary-button" href="/tournaments/manage">{tr("Управление мероприятиями","Іс-шараларды басқару","Иш-чараларды башкаруу")}</Link><form className="cyber-card space-y-3 p-5" onSubmit={e=>{e.preventDefault();void act({domain:"organizer",action:"apply",message:new FormData(e.currentTarget).get("message")});}}><h2 className="text-xl font-bold">{tr("Золотой статус организатора","Ұйымдастырушының алтын мәртебесі","Уюштуруучунун алтын макамы")}</h2><textarea required maxLength={5000} name="message" aria-label={tr("Заявка","Өтінім","Өтүнмө")} className={inputClass}/><button className="primary-button" disabled={busy||data.applications.some(a=>a.user_id===data.actor&&["pending","approved"].includes(a.status))}>{t("send")}</button></form>{data.applications.map(a=><article className="cyber-card space-y-3 p-5" key={a.user_id}><p>{name(a.user_id)} · {a.status==="pending"?t("pending"):a.status==="approved"?t("approve"):a.status==="rejected"?t("reject"):a.status==="suspended"?tr("Приостановлено","Тоқтатылды","Токтотулду"):tr("Отозвано","Кері қайтарылды","Кайтарылды")}</p><p className="whitespace-pre-wrap">{a.message}</p>{data.isAdmin&&<div className="flex flex-wrap gap-3">{(["approved","rejected","suspended","revoked"] as const).map(status=><button className="secondary-button" key={status} disabled={busy||a.status===status} onClick={()=>void act({domain:"organizer",action:"review",userId:a.user_id,status})}>{status==="approved"?t("approve"):status==="rejected"?t("reject"):status==="suspended"?tr("Приостановить","Тоқтату","Токтотуу"):tr("Отозвать","Кері қайтару","Кайтаруу")}</button>)}</div>}</article>)}</>}
 </main>;
}
