"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {authFetch} from "@/utils/api/auth-fetch";
import {useLanguage} from "./LanguageProvider";
import {competitionText} from "@/i18n/competition";
import {importRecords,type ImportRecord,type ImportMapping} from "@/lib/competition/import";
import type {CompetitionContext,ResultInput} from "@/lib/competition/model";
import type {Worker} from "tesseract.js";
type Evidence={id:string;gameId:string;name:string;url:string};
export default function CompetitionEvidence({eventId,apiBase,sessionId,publicId,context,disabled,onRows,onReplay}:{eventId:string;apiBase?:string;sessionId:string;publicId:string;context:CompetitionContext;disabled:boolean;onRows:(rows:ResultInput[])=>void;onReplay:(gameId:string)=>void}){
 const {locale}=useLanguage();const t=(key:Parameters<typeof competitionText>[1])=>competitionText(locale,key);const tr=(ru:string,kk:string,ky:string)=>locale==="kk"?kk:locale==="ky"?ky:ru;
 const [game,setGame]=useState(context.games[0]?.id??""),[files,setFiles]=useState<Evidence[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [ocrText,setOcrText]=useState(""),[recognition,setRecognition]=useState<ImportRecord[]>([]),[mapping,setMapping]=useState<Record<string,ImportMapping>>({}),[ocrMode,setOcrMode]=useState("team");
 const worker=useRef<Worker|null>(null),mounted=useRef(true);const endpoint=`${apiBase??`/api/admin/events/${eventId}/competition-results`}/evidence`;
 const load=useCallback(async()=>{try{const r=await authFetch(`${endpoint}?sessionId=${sessionId}`),data=await r.json();if(!r.ok)throw new Error(data.error);setFiles(data.files);}catch(e){setMessage(e instanceof Error?e.message:"Ошибка загрузки");}},[endpoint,sessionId]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;const current=worker.current;worker.current=null;void current?.terminate();};},[]);
 const selected=context.games.find(g=>g.id===game),entrants=context.entrants.filter(e=>e.groupId===selected?.groupId);
 const act=async(action:"add"|"remove"|"replay",inputFiles?:FileList|null,evidenceId?:string)=>{setBusy(true);setMessage("");try{const form=new FormData();form.set("sessionId",sessionId);form.set("gameId",game);form.set("action",action);if(evidenceId)form.set("evidenceId",evidenceId);for(const file of Array.from(inputFiles??[]))form.append("files",file);const r=await authFetch(endpoint,{method:"POST",body:form}),data=await r.json();if(!r.ok)throw new Error(data.error);if(action==="replay")onReplay(game);await load();}catch(e){setMessage(e instanceof Error?e.message:t("failed"));}finally{setBusy(false);}};
 const recognize=async(input:FileList|null)=>{if(!input?.length)return;setBusy(true);setMessage("");try{
  if(input.length>10||Array.from(input).some(f=>f.size>10*1024*1024||!["image/jpeg","image/png"].includes(f.type)))throw new Error(tr("До 10 JPG/PNG, каждый до 10 МБ","10 JPG/PNG дейін, әрқайсысы 10 МБ дейін","10 JPG/PNG чейин, ар бири 10 МБ чейин"));
  const {createWorker,OEM}=await import("tesseract.js");const engine=await createWorker(["eng","rus"],OEM.LSTM_ONLY,{logger:info=>{if(mounted.current)setMessage(`OCR: ${Math.round(info.progress*100)}%`);}});if(!mounted.current){await engine.terminate();return;}worker.current=engine;
  const pieces=[];for(const file of Array.from(input)){if(!mounted.current)break;pieces.push((await engine.recognize(file)).data.text);}if(mounted.current){setOcrText(pieces.join("\n"));setMessage(tr("Распознавание готово. Исправьте текст и проверьте каждую строку.","Тану аяқталды. Мәтінді түзетіп, әр жолды тексеріңіз.","Таануу бүттү. Текстти оңдоп, ар бир сапты текшериңиз."));}
 }catch(e){if(mounted.current)setMessage(e instanceof Error?e.message:t("failed"));}finally{const current=worker.current;worker.current=null;await current?.terminate();if(mounted.current)setBusy(false);}};
 const parseText=()=>{const records:ImportRecord[]=[];for(const source of ocrText.split(/\r?\n/)){const text=source.replace(/\s+/g," ").trim();const match=ocrMode==="team"?text.match(/^(\d{1,4})\s+(.+?)\s+(\d+)$/u):text.match(/^(.+?)\s+(\d+)(?:\s+(\d+)\s+(\d+))?$/u);if(!match)continue;
  records.push(ocrMode==="team"?{game_id:game,place:match[1],team:match[2],kills:match[3],played:"1"}:{game_id:game,nickname:match[1],kills:match[2],deaths:match[3]??"",assists:match[4]??"",played:"1"});}
 setRecognition(records);setMapping({});if(!records.length)setMessage(tr("Строки не распознаны. Формат: место команда убийства; либо ник убийства смерти помощи.","Жолдар танылмады. Пішім: орын команда өлтірулер; не ник өлтірулер өлімдер көмектер.","Саптар таанылган жок. Формат: орун команда өлтүрүүлөр; же ник өлтүрүүлөр өлүмдөр жардамдар."));};
 return <section className="cyber-card space-y-4 p-4"><h2 className="font-bold">{t("evidence")}</h2><label>{t("game")}<select className="ml-2" value={game} disabled={busy} onChange={e=>{setGame(e.target.value);setRecognition([]);}}>{context.games.map(g=><option key={g.id} value={g.id}>{g.publicId} · {g.map}</option>)}</select></label><div className="flex flex-wrap gap-3"><label className="secondary-button">{t("upload")} JPG/PNG<input className="block text-sm" type="file" accept="image/jpeg,image/png" multiple disabled={disabled||busy||!game} onChange={e=>{void act("add",e.target.files);e.target.value="";}}/></label><button disabled={busy} className="secondary-button" onClick={async()=>{setBusy(true);try{const r=await authFetch(`${endpoint}?sessionId=${sessionId}&zip=1`);if(!r.ok)throw new Error((await r.json()).error);const url=URL.createObjectURL(await r.blob()),a=document.createElement("a");a.href=url;a.download=`evidence-${publicId}.zip`;a.click();URL.revokeObjectURL(url);}catch(e){setMessage(e instanceof Error?e.message:t("failed"));}finally{setBusy(false);}}}>ZIP · {t("session")}</button><button disabled={disabled||busy||!game} className="secondary-button" onClick={()=>{if(window.confirm(tr("Начать переигровку? Доказательства этой игры будут удалены, её поля в черновике очищены. Опубликованный итог заменится после сохранения исправлений.","Қайта ойнау басталсын ба? Дәлелдер жойылып, жоба өрістері тазартылады. Жарияланған нәтиже түзетулер сақталғанда ауысады.","Кайра ойноо башталсынбы? Далилдер өчүрүлүп, долбоор тазаланат. Жарыяланган жыйынтык оңдоолор сакталганда алмашат.")))void act("replay");}}>{tr("Переигровка","Қайта ойнау","Кайра ойноо")}</button></div>
 {message&&<p role="status" className="whitespace-pre-wrap">{message}</p>}<div className="flex flex-wrap gap-3">{files.filter(f=>f.gameId===game).map(file=><div key={file.id} className="max-w-44 rounded-lg border border-white/10 p-2"><a href={file.url} target="_blank" rel="noreferrer" className="break-all text-cyan-300">{file.name}</a><button className="mt-2 block text-red-300" disabled={disabled||busy} onClick={()=>void act("remove",null,file.id)}>{t("remove")}</button></div>)}</div>
 <details className="border-t border-white/15 pt-3"><summary className="cursor-pointer">{tr("Распознать скриншоты в браузере (бесплатно)","Скриншоттарды браузерде тану (тегін)","Скриншотторду браузерде таануу (акысыз)")}</summary><div className="mt-3 space-y-3"><input aria-label="OCR JPG/PNG" type="file" accept="image/jpeg,image/png" multiple disabled={busy||disabled} onChange={e=>void recognize(e.target.files)}/><select value={ocrMode} onChange={e=>setOcrMode(e.target.value)}><option value="team">{t("teamOnly")}</option><option value="players">{t("detail")}</option></select><textarea aria-label="OCR" className="min-h-40 w-full rounded-lg bg-slate-950 p-3" value={ocrText} onChange={e=>setOcrText(e.target.value)}/><button className="secondary-button" disabled={!ocrText||busy||disabled} onClick={parseText}>{tr("Разобрать строки","Жолдарды талдау","Саптарды талдоо")}</button>
 {recognition.map((row,i)=>{const m=mapping[String(i+2)]??{},available=m.registrationId?entrants.filter(e=>e.id===m.registrationId):entrants;return <div className="grid gap-2 rounded-lg border border-white/15 p-3 sm:grid-cols-4" key={i}><input aria-label={ocrMode==="team"?t("team"):t("player")} value={row.team??row.nickname??""} onChange={e=>setRecognition(r=>r.map((v,n)=>n===i?{...v,[ocrMode==="team"?"team":"nickname"]:e.target.value}:v))}/><label>{t("target")}<select value={m.registrationId??""} onChange={e=>setMapping(v=>({...v,[i+2]:{...m,registrationId:e.target.value||undefined,userId:undefined}}))}><option value="">{t("choose")}</option>{entrants.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label>{ocrMode==="players"&&<label>{t("player")}<select value={m.guest?"guest":m.userId??""} onChange={e=>setMapping(v=>({...v,[i+2]:{...m,userId:e.target.value&&e.target.value!=="guest"?e.target.value:undefined,guest:e.target.value==="guest"}}))}><option value="">{t("choose")}</option><option value="guest">{t("guest")}</option>{available.flatMap(e=>e.roster.map(p=><option key={`${e.id}:${p.id}`} value={p.id}>{p.nickname} · {p.gameId}</option>))}</select></label>}{([...(ocrMode==="team"?["place"]:[]),"kills",...(ocrMode==="players"&&["bo","kv"].includes(context.rules.mode)?["deaths","assists"]:[])] as Array<"place"|"kills"|"deaths"|"assists">).map(key=><label key={key}>{t(key)}<input type="number" min={key==="place"?1:0} value={row[key]??""} onChange={e=>setRecognition(r=>r.map((v,n)=>n===i?{...v,[key]:e.target.value}:v))}/></label>)}<button className="text-red-300" onClick={()=>{setRecognition(r=>r.filter((_,n)=>n!==i));setMapping({});}}>{t("remove")}</button></div>;})}
 {!!recognition.length&&<button className="primary-button" disabled={disabled||busy} onClick={()=>{const result=importRecords(context,recognition,mapping);if(result.unresolved.length){setMessage(result.unresolved.map(r=>`${r.line}: ${r.reason}`).join("\n"));return;}const touched=new Set(result.affectedRowKeys);onRows(result.rows.filter(r=>touched.has(`${r.gameId}:${r.registrationId}`)));setRecognition([]);setMessage(t("saved"));}}>{tr("Проверено: перенести в черновик","Тексерілді: жобаға көшіру","Текшерилди: долбоорго көчүрүү")}</button>}</div></details></section>;
}
