"use client";
import EventLifecycle from "./EventLifecycle";
import Link from "next/link";
import {useCallback,useEffect,useRef,useState,type ReactNode} from "react";
import {authFetch} from "@/utils/api/auth-fetch";
import {useLanguage} from "./LanguageProvider";
import {eventText} from "@/i18n/event-editor";
import {defaultPlacePoints,maps} from "@/lib/competition/model";
import type {EventConfiguration} from "@/lib/competition/event-schema";
type Session=EventConfiguration["sessions"][number];
const newGroup=()=>({id:crypto.randomUUID(),name:"",capacity:12,roomId:"",roomPassword:"",roomNote:"",games:[{id:crypto.randomUUID(),map:"bermuda" as const}]});
const newSession=():Session=>({id:crypto.randomUUID(),startTime:"",endTime:"",registrationOpenTime:null,registrationCloseTime:null,maxTeams:12,responsibleUserId:null,description:"",stage:"ordinary",sourceSessionId:null,qualification:{mode:"general",count:1,transfer:"none",value:0},reminderMinutes:[60],groups:[newGroup()]});
function initial():EventConfiguration{return {title:"",type:"training",cost:0,organizer:"",organizerUserId:null,description:"",rulesText:"",streamUrl:"",paymentUrl:"",imageUrl:"",maxTeams:12,minPlayers:4,rosterLockMinutes:10,publishAt:null,commentsEnabled:true,allowIndividualRegistration:false,finalSessionId:null,rules:{mode:"training",criterion:"points",placePoints:defaultPlacePoints,killPoints:1,bonuses:{},nominations:["points"],ratingEnabled:true,winsRequired:1},sessions:[]};}
function localDate(iso:string|null){return iso?new Date(Date.parse(iso)+3*3600_000).toISOString().slice(0,16):"";}
function isoDate(value:string){return value?new Date(`${value}:00+03:00`).toISOString():null;}
const fieldClass="grid gap-1 text-sm [&_input]:w-full [&_input]:rounded-lg [&_input]:border [&_input]:border-white/20 [&_input]:bg-slate-950 [&_input]:p-2 [&_select]:bg-slate-950 [&_select]:p-2 [&_textarea]:min-h-24 [&_textarea]:bg-slate-950 [&_textarea]:p-2";
function Field({label,children}:{label:string;children:ReactNode}){return <label className={fieldClass}><span className="text-white/70">{label}</span>{children}</label>;}
export function EventManager({reviewOnly=false}:{reviewOnly?:boolean}){
 const {locale}=useLanguage();const t=(key:Parameters<typeof eventText>[1])=>eventText(locale,key);
 const [query,setQuery]=useState(""),[visible,setVisible]=useState(20);
 const [events,setEvents]=useState<Array<{id:string;title:string;moderation_status:"pending"|"approved"|"rejected"|"frozen";pending_changes:unknown}>>([]),[message,setMessage]=useState("");
 useEffect(()=>{let alive=true;void authFetch("/api/events/editor").then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);if(alive)setEvents(data.events);}).catch(e=>{if(alive)setMessage(e.message);});return()=>{alive=false;};},[]);
 return <main className="page-shell space-y-5"><h1 className="text-3xl font-black">{t("manage")}</h1><Link href="/tournaments/propose" className="primary-button">{t("create")}</Link><label className="block">{t("search")}<input className="ml-2" value={query} onChange={e=>{setQuery(e.target.value);setVisible(20);}}/></label>{message&&<p role="alert">{message}</p>}{!events.length&&!message&&<p>{t("empty")}</p>}<div className="grid gap-3">{events.filter(e=>(!reviewOnly||e.moderation_status==="pending"||!!e.pending_changes)&&e.title.toLocaleLowerCase().includes(query.toLocaleLowerCase())).slice(0,visible).map(e=><article key={e.id} className="cyber-card flex flex-wrap items-center justify-between gap-4 p-5"><div><Link href={`/tournaments/${e.id}`} className="text-xl font-bold">{e.title}</Link><p>{e.pending_changes?t("pending"):t(e.moderation_status)}</p></div><div className="flex gap-4"><Link className="text-cyan-300" href={`/tournaments/${e.id}/edit`}>{t("edit")}</Link><Link className="text-cyan-300" href={`/tournaments/${e.id}/manage-results`}>{t("results")}</Link></div></article>)}</div>{events.filter(e=>(!reviewOnly||e.moderation_status==="pending"||!!e.pending_changes)&&e.title.toLocaleLowerCase().includes(query.toLocaleLowerCase())).length>visible&&<button className="secondary-button" onClick={()=>setVisible(n=>n+20)}>{t("more")}</button>}</main>;
}
export default function EventEditor({eventId}:{eventId?:string}){
 const {locale}=useLanguage();const t=(key:Parameters<typeof eventText>[1])=>eventText(locale,key);
 const [config,setConfig]=useState<EventConfiguration>(initial),[id,setId]=useState(eventId??null),[revision,setRevision]=useState(0),[admin,setAdmin]=useState(false),[pending,setPending]=useState<EventConfiguration|null>(null);
 const [busy,setBusy]=useState(true),[message,setMessage]=useState(""),[image,setImage]=useState<File|null>(null),[dirty,setDirty]=useState(false);
 const [review,setReview]=useState<{approve:boolean;effects:Array<{sessionId:string;removedGames:number;reordered:boolean;rulesChanged:boolean}>}|null>(null);
 const [moderationStatus,setModerationStatus]=useState("approved");
 const saved=useRef(""),dirtyRef=useRef(false);
 const load=useCallback(async(event?:string)=>{setBusy(true);try{const r=await authFetch(`/api/events/editor${event?`?id=${event}`:""}`),d=await r.json();if(!r.ok)throw new Error(d.error);setAdmin(d.isAdmin);if(event){setConfig(d.pendingChanges??d.config);setModerationStatus(d.moderationStatus);setRevision(d.revision);setPending(d.pendingChanges);saved.current=JSON.stringify(d.pendingChanges??d.config);}else{const fresh={...initial(),sessions:[newSession()]};setConfig(fresh);saved.current=JSON.stringify(fresh);}dirtyRef.current=false;setDirty(false);}catch(e){setMessage(e instanceof Error?e.message:"Ошибка загрузки");}finally{setBusy(false);}},[]);
 useEffect(()=>{const timer=setTimeout(()=>void load(eventId),0);return()=>clearTimeout(timer);},[eventId,load]);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(!dirtyRef.current)return;e.preventDefault();e.returnValue="";};window.addEventListener("beforeunload",handler);return()=>window.removeEventListener("beforeunload",handler);},[]);
 const change=(patch:Partial<EventConfiguration>)=>{setConfig(c=>({...c,...patch}));dirtyRef.current=true;setDirty(true);};
 const sessionChange=(index:number,patch:Partial<Session>)=>change({sessions:config.sessions.map((s,i)=>i===index?{...s,...patch}:s)});
 const save=async(approve=false,reviewed=false)=>{setBusy(true);setMessage("");try{if(id&&!reviewed){const r=await authFetch("/api/events/editor",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,revision,config,approve,preview:true})}),d=await r.json();if(!r.ok)throw new Error(d.error);if(d.effects?.length){setReview({approve,effects:d.effects});return;}}const form=new FormData();form.set("payload",JSON.stringify({id,revision,config,approve}));if(image)form.set("image",image);
  const response=await authFetch("/api/events/editor",{method:"POST",body:form}),value=await response.json();if(!response.ok)throw new Error(value.issues?.map((issue:{path:string[];message:string})=>`${issue.path.join(" / ")}: ${issue.message}`).join("\n")??value.error);
  setModerationStatus(value.pending?(id?moderationStatus:"pending"):"approved");setId(value.eventId);setRevision(value.revision);saved.current=JSON.stringify(config);dirtyRef.current=false;setDirty(false);setImage(null);setReview(null);setPending(value.pending?config:null);setMessage(value.pending?t("review"):t("saved"));
 }catch(error){setMessage(error instanceof Error?error.message:t("error"));}finally{setBusy(false);}};
 const ruleChange=(patch:Partial<EventConfiguration["rules"]>)=>change({rules:{...config.rules,...patch}});
 const numberField=(key:"cost"|"maxTeams"|"minPlayers",label:Parameters<typeof eventText>[1],min=0,max=1024)=><Field label={t(label)}><input type="number" min={min} max={max} required value={config[key]} onChange={e=>change({[key]:Number(e.target.value)})}/></Field>;
 return <main className="page-shell space-y-6"><Link href="/tournaments/manage" className="text-cyan-300">← {t("back")}</Link><h1 className="text-3xl font-black">{t(id?"edit":"create")}</h1><p className="text-white/60">{t("msk")} · {t("lock")}</p>
 {message&&<p role="status" className="whitespace-pre-line rounded-xl border border-white/20 p-4">{message}</p>}
 {pending&&<aside className="cyber-card space-y-3 p-4"><p>{t("pending")}: {pending.title}</p><button className="secondary-button" onClick={()=>{setConfig(pending);setDirty(true);}}>{t("loadPending")}</button></aside>}
 {review&&<section role="dialog" aria-label={t("consequences")} className="cyber-card space-y-3 border border-amber-500/40 p-4"><h2 className="font-bold">{t("consequences")}</h2><p>{t("recalculateNotice")}</p>{review.effects.map(e=><p key={e.sessionId}>{t("session")}: {config.sessions.findIndex(s=>s.id===e.sessionId)+1} · {t("removedGames")}: {e.removedGames}</p>)}<button className="primary-button" disabled={busy} onClick={()=>void save(review.approve||(admin&&review.effects.some(e=>e.removedGames>0)),true)}>{t("confirmChanges")}</button><button className="secondary-button" onClick={()=>setReview(null)}>{t("cancel")}</button></section>}
 <form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy} className="space-y-6">
 <section className="cyber-card grid gap-4 p-5 sm:grid-cols-2"><Field label={t("title")}><input required minLength={2} maxLength={160} value={config.title} onChange={e=>change({title:e.target.value})}/></Field><Field label={t("format")}><select value={config.type} onChange={e=>{const mode=e.target.value as EventConfiguration["type"];change({type:mode,rules:{...config.rules,mode},allowIndividualRegistration:mode==="solo",minPlayers:mode==="solo"?1:4,sessions:config.sessions.map(s=>({...s,groups:s.groups.map(g=>({...g,capacity:mode==="solo"?60:["bo","kv"].includes(mode)?2:Math.min(15,g.capacity)}))}))});}}>{["training","tournament","solo","bo","kv"].map(mode=><option key={mode} value={mode}>{t(mode as "training")}</option>)}</select></Field>
 {numberField("cost","fee",0,10000000)}{numberField("maxTeams","limit",1)}{numberField("minPlayers","minPlayers",1)}<Field label={t("organizer")}><input value={config.organizer} onChange={e=>change({organizer:e.target.value})}/></Field>{admin&&!id&&<Field label={t("organizerId")}><input value={config.organizerUserId??""} onChange={e=>change({organizerUserId:e.target.value||null})}/></Field>}
 {(["streamUrl","paymentUrl"] as const).map((key,i)=><Field key={key} label={t(i?"payment":"stream")}><input type="url" value={config[key]} onChange={e=>change({[key]:e.target.value})}/></Field>)}<Field label={t("image")}><input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>{setImage(e.target.files?.[0]??null);dirtyRef.current=true;setDirty(true);}}/></Field><Field label={t("publishAt")}><input type="datetime-local" value={localDate(config.publishAt)} onChange={e=>change({publishAt:isoDate(e.target.value)})}/></Field>
 {(["description","rulesText"] as const).map((key,i)=><Field key={key} label={t(i?"rules":"description")}><textarea maxLength={10000} value={config[key]} onChange={e=>change({[key]:e.target.value})}/></Field>)}<label><input type="checkbox" checked={config.commentsEnabled} onChange={e=>change({commentsEnabled:e.target.checked})}/> {t("comments")}</label><label><input type="checkbox" disabled={config.type==="solo"} checked={config.allowIndividualRegistration} onChange={e=>change({allowIndividualRegistration:e.target.checked})}/> {t("individual")}</label></section>
 <section className="cyber-card grid gap-4 p-5 sm:grid-cols-2"><h2 className="text-xl font-bold sm:col-span-2">{t("rules")}</h2><Field label={t("criterion")}><select value={config.rules.criterion} onChange={e=>ruleChange({criterion:e.target.value as "points"})}>{["points","kills","places"].map(c=><option key={c} value={c}>{t(c as "points")}</option>)}</select></Field><Field label={t("placePoints")}><input key={`${id??"new"}:${config.rules.placePoints.join(",")}`} defaultValue={config.rules.placePoints.join(", ")} onBlur={e=>ruleChange({placePoints:e.target.value.split(/[,;\s]+/).filter(Boolean).map(Number)})}/></Field><Field label={t("killPoints")}><input type="number" min={0} step="any" value={config.rules.killPoints} onChange={e=>ruleChange({killPoints:Number(e.target.value)})}/></Field><label><input type="checkbox" checked={config.rules.ratingEnabled} onChange={e=>ruleChange({ratingEnabled:e.target.checked})}/> {t("rating")}</label>
 {config.type==="solo"&&<div><p>{t("nominations")}</p>{(["points","kills","places"] as const).map(n=><label key={n} className="mr-4"><input type="checkbox" checked={config.rules.nominations.includes(n)} onChange={e=>ruleChange({nominations:e.target.checked?[...config.rules.nominations,n]:config.rules.nominations.filter(k=>k!==n)})}/> {t(n)}</label>)}</div>}{["bo","kv"].includes(config.type)&&<Field label={t("winsRequired")}><input type="number" min={1} value={config.rules.winsRequired} onChange={e=>ruleChange({winsRequired:Number(e.target.value)})}/></Field>}
 <Field label={t("finalSession")}><select value={config.finalSessionId??""} onChange={e=>change({finalSessionId:e.target.value||null})}><option value="">{t("none")}</option>{config.sessions.map((s,i)=><option key={s.id} value={s.id}>{t("session")} {i+1}</option>)}</select></Field></section>
 {config.sessions.map((s,i)=><section key={s.id} className="cyber-card space-y-4 p-5"><div className="flex justify-between"><h2 className="text-xl font-bold">{t("session")} {i+1}</h2><button type="button" disabled={config.sessions.length<2} onClick={()=>change({sessions:config.sessions.filter((_,n)=>i!==n)})}>{t("remove")}</button></div><div className="grid gap-4 sm:grid-cols-2">
 {(["startTime","endTime","registrationOpenTime","registrationCloseTime"] as const).map((key,n)=><Field key={key} label={t((["start","end","regOpen","regClose"] as const)[n])}><input type="datetime-local" required={n<2} value={localDate(s[key])} onChange={e=>sessionChange(i,{[key]:isoDate(e.target.value)??(n<2?"":null)})}/></Field>)}<Field label={t("limit")}><input type="number" min={1} max={1024} value={s.maxTeams} onChange={e=>sessionChange(i,{maxTeams:Number(e.target.value)})}/></Field><Field label={t("responsible")}><input value={s.responsibleUserId??""} onChange={e=>sessionChange(i,{responsibleUserId:e.target.value||null})}/></Field><Field label={t("description")}><textarea value={s.description} onChange={e=>sessionChange(i,{description:e.target.value})}/></Field><Field label={t("reminders")}><input key={`${s.id}:${s.reminderMinutes.join(",")}`} defaultValue={s.reminderMinutes.join(", ")} onBlur={e=>sessionChange(i,{reminderMinutes:e.target.value.split(/[,;\s]+/).filter(Boolean).map(Number)})}/></Field><Field label={t("stage")}><select value={s.stage} onChange={e=>sessionChange(i,{stage:e.target.value as Session["stage"]})}>{["ordinary","qualification","semifinal","final"].map(stage=><option key={stage} value={stage}>{t(stage as "ordinary")}</option>)}</select></Field><Field label={t("source")}><select value={s.sourceSessionId??""} onChange={e=>sessionChange(i,{sourceSessionId:e.target.value||null})}><option value="">{t("none")}</option>{config.sessions.map((src,n)=>n!==i&&<option key={src.id} value={src.id}>{t("session")} {n+1}</option>)}</select></Field>
 <Field label={t("qualifyMode")}><select value={s.qualification.mode} onChange={e=>sessionChange(i,{qualification:{...s.qualification,mode:e.target.value as "general"}})}><option value="general">{t("general")}</option><option value="group">{t("perGroup")}</option></select></Field><Field label={t("qualifyCount")}><input type="number" min={1} max={1024} value={s.qualification.count} onChange={e=>sessionChange(i,{qualification:{...s.qualification,count:Number(e.target.value)}})}/></Field><Field label={t("transfer")}><select value={s.qualification.transfer} onChange={e=>sessionChange(i,{qualification:{...s.qualification,transfer:e.target.value as "none"}})}>{["none","all","percent","bonus"].map(x=><option key={x} value={x}>{t(x as "none")}</option>)}</select></Field>{["percent","bonus"].includes(s.qualification.transfer)&&<Field label={t("value")}><input type="number" min={0} max={s.qualification.transfer==="percent"?100:1000000} value={s.qualification.value} onChange={e=>sessionChange(i,{qualification:{...s.qualification,value:Number(e.target.value)}})}/></Field>}</div>
 <button type="button" className="secondary-button" onClick={()=>{const capacity=s.groups[0]?.capacity??12;const missing=Math.max(0,Math.min(1024,s.maxTeams)-s.groups.reduce((total,g)=>total+g.capacity,0));sessionChange(i,{groups:[...s.groups,...Array.from({length:Math.ceil(missing/Math.max(2,capacity))},()=>({...newGroup(),capacity,games:(s.groups[0]?.games??[{map:"bermuda" as const}]).map(g=>({id:crypto.randomUUID(),map:g.map}))}))]});}}>{t("fillGroups")}</button>{s.groups.map((g,j)=>{const update=(patch:Partial<typeof g>)=>sessionChange(i,{groups:s.groups.map((x,n)=>n===j?{...g,...patch}:x)});return <div key={g.id} className="space-y-3 rounded-xl border border-white/15 p-4"><div className="flex items-center justify-between"><h3>{t("group")} {j+1}</h3><button type="button" disabled={s.groups.length<2} onClick={()=>sessionChange(i,{groups:s.groups.filter((_,n)=>n!==j)})}>{t("remove")}</button></div><div className="grid gap-3 sm:grid-cols-2"><Field label={t("title")}><input value={g.name} onChange={e=>update({name:e.target.value})}/></Field><Field label={t("capacity")}><input type="number" min={2} max={config.type==="solo"?60:["bo","kv"].includes(config.type)?2:15} value={g.capacity} onChange={e=>update({capacity:Number(e.target.value)})}/></Field></div><div className="grid gap-3 sm:grid-cols-3">{(["roomId","roomPassword","roomNote"] as const).map(key=><Field key={key} label={t(key)}><input value={g[key]??""} maxLength={key==="roomNote"?2000:100} onChange={e=>update({[key]:e.target.value})}/></Field>)}</div><div className="grid gap-2 sm:grid-cols-2">{g.games.map((game,n)=><div key={game.id} className="flex items-center gap-2"><label>{t("game")} {n+1}<select className="ml-2 bg-slate-950 p-2" value={game.map} onChange={e=>update({games:g.games.map((x,k)=>k===n?{...x,map:e.target.value as typeof game.map}:x)})}>{maps.map(map=><option key={map}>{map}</option>)}</select></label><button type="button" aria-label={`${t("game")} ${n+1} ↑`} disabled={!n} onClick={()=>{const games=[...g.games];[games[n-1],games[n]]=[games[n],games[n-1]];update({games});}}>↑</button><button type="button" disabled={g.games.length<2} onClick={()=>update({games:g.games.filter((_,k)=>k!==n)})}>{t("remove")}</button></div>)}</div><button type="button" className="secondary-button" onClick={()=>update({games:[...g.games,{id:crypto.randomUUID(),map:"bermuda"}]})}>+ {t("addGame")}</button></div>;})}<button type="button" className="secondary-button" onClick={()=>sessionChange(i,{groups:[...s.groups,{...newGroup(),capacity:config.type==="solo"?60:["bo","kv"].includes(config.type)?2:12}]})}>+ {t("addGroup")}</button></section>)}
 <div className="flex flex-wrap gap-4"><button type="button" className="secondary-button" onClick={()=>change({sessions:[...config.sessions,{...newSession(),groups:[{...newGroup(),capacity:config.type==="solo"?60:["bo","kv"].includes(config.type)?2:12}]}]})}>+ {t("addSession")}</button><button className="primary-button" type="submit">{busy?t("loading"):t("save")}</button>{admin&&id&&<button className="secondary-button" type="button" onClick={()=>void save(true)}>{t("approve")}</button>}{admin&&id&&(pending||moderationStatus==="pending")&&<button className="secondary-button" type="button" disabled={busy} onClick={async()=>{const reason=window.prompt(t("rejectReason"));if(!reason)return;setBusy(true);try{const r=await authFetch("/api/events/editor/review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,revision,reason})}),d=await r.json();if(!r.ok)throw new Error(d.error);await load(id);setMessage(t("rejected"));}catch(e){setMessage(e instanceof Error?e.message:t("error"));}finally{setBusy(false);}}}>{t("reject")}</button>}{dirty&&<span className="self-center text-amber-300">{t("unsaved")}</span>}</div></fieldset></form>{id&&<EventLifecycle key={`${id}:${revision}`} id={id} disabled={dirty||busy}/>}</main>;
}
