"use client";
import Link from "next/link";
import {useCallback,useEffect,useRef,useState} from "react";
import {authFetch} from "@/utils/api/auth-fetch";
import {useLanguage} from "./LanguageProvider";
import type {Standing,RosterPlayer} from "@/lib/competition/model";
interface Registration{id:string;team_id:string|null;participant_user_id:string|null;status:string;group_id:string|null;roster_json:string[];roster_snapshot:RosterPlayer[]|null;name_snapshot:string|null;carried_points:number}
interface Data{event:{id:string;title:string};session:{id:string;start_time:string};groups:Array<{id:string;public_number:number;name:string}>;registrations:Registration[];revision:number;role:string;mode:string;published:boolean;serverTime:string;
 source:{revision:number;standings:Standing[]}|null;qualification:{suggested:Standing[];selected_ids:string[];confirmed_at:string|null;needs_review:boolean}|null}
interface Candidate{id:string;name?:string;nickname?:string;game_id?:string|null}
export default function RegistrationManager({eventId}:{eventId:string}){
 const {locale}=useLanguage(),tr=(ru:string,kk:string,ky:string)=>locale==="kk"?kk:locale==="ky"?ky:ru;
 const [data,setData]=useState<Data|null>(null),[sessions,setSessions]=useState<Array<{id:string;start_time:string}>>([]),[sessionId,setSessionId]=useState("");
 const [message,setMessage]=useState(""),[busy,setBusy]=useState(false),[query,setQuery]=useState(""),[targetType,setTargetType]=useState<"team"|"player">("team"),[candidates,setCandidates]=useState<Candidate[]>([]);
 const [target,setTarget]=useState<Candidate|null>(null),[players,setPlayers]=useState<Candidate[]>([]),[roster,setRoster]=useState<string[]>([]),[groupId,setGroupId]=useState(""),[editing,setEditing]=useState<string|null>(null),[status,setStatus]=useState("confirmed");
 const [selectedIds,setSelectedIds]=useState<string[]>([]),[confirmStarted,setConfirmStarted]=useState(false);
 const [registrationQuery,setRegistrationQuery]=useState(""),[visibleCount,setVisibleCount]=useState(50),[qualificationQuery,setQualificationQuery]=useState(""),[qualificationCount,setQualificationCount]=useState(50);
 const requestVersion=useRef(0);
 const endpoint=`/api/events/${eventId}/participants`;
 const load=useCallback(async(id:string)=>{const version=++requestVersion.current;setBusy(true);try{const r=await authFetch(`${endpoint}?sessionId=${id}`),d=await r.json();if(version!==requestVersion.current)return;if(!r.ok)throw new Error(d.error);setData(d);setSessionId(id);setSelectedIds(d.qualification?.confirmed_at?d.qualification.selected_ids:(d.qualification?.suggested??[]).map((x:Standing)=>x.registrationId));setVisibleCount(50);setQualificationCount(50);setEditing(null);setTarget(null);setConfirmStarted(false);}finally{if(version===requestVersion.current)setBusy(false);}},[endpoint]);
 useEffect(()=>{const versionRef=requestVersion;let alive=true;const timer=setTimeout(()=>{void authFetch(`/api/admin/events/${eventId}/competition-results`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);if(!alive)return;setSessions(d.sessions);const requested=new URLSearchParams(location.search).get("sessionId");const id=d.sessions.find((s:{id:string})=>s.id===requested)?.id??d.sessions[0]?.id;if(id)await load(id);}).catch(e=>{if(alive)setMessage(e.message);});},0);return()=>{alive=false;++versionRef.current;clearTimeout(timer);};},[eventId,load]);
 const act=async(change:Record<string,unknown>)=>{if(!data)return;setBusy(true);setMessage("");try{const r=await authFetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId,revision:data.revision,requestId:crypto.randomUUID(),change:{...change,confirmStarted}})}),d=await r.json();if(!r.ok)throw new Error(d.error);await load(sessionId);setEditing(null);setTarget(null);setMessage(tr("Сохранено","Сақталды","Сакталды"));}catch(e){setMessage(e instanceof Error?e.message:"Ошибка");}finally{setBusy(false);}};
 const search=async()=>{setBusy(true);try{const r=await authFetch(`${endpoint}?sessionId=${sessionId}&lookup=${targetType}&q=${encodeURIComponent(query)}`),d=await r.json();if(!r.ok)throw new Error(d.error);setCandidates(d.items);}catch(e){setMessage(e instanceof Error?e.message:"Ошибка");}finally{setBusy(false);}};
 const choose=async(item:Candidate,kind:typeof targetType,ids:string[]=[])=>{setTarget(item);setRoster(kind==="player"?[item.id]:ids);setPlayers([]);if(kind==="team"){setBusy(true);try{const r=await authFetch(`${endpoint}?sessionId=${sessionId}&teamId=${item.id}`),d=await r.json();if(!r.ok)throw new Error(d.error);setPlayers(d.players);}catch(e){setMessage(e instanceof Error?e.message:"Ошибка");}finally{setBusy(false);}}};
 const registrations=(data?.registrations??[]).filter(r=>r.status!=="cancelled"&&`${r.name_snapshot??""} ${(r.roster_snapshot??[]).map(p=>`${p.nickname} ${p.gameId??""}`).join(" ")}`.toLocaleLowerCase().includes(registrationQuery.toLocaleLowerCase()));
 const qualifiers=(data?.source?.standings??[]).filter(s=>s.name.toLocaleLowerCase().includes(qualificationQuery.toLocaleLowerCase()));
 const started=!!data&&Date.parse(data.session.start_time)<=Date.parse(data.serverTime);
 return <main className="page-shell space-y-5"><Link className="text-cyan-300" href={`/tournaments/${eventId}`}>{tr("К мероприятию","Іс-шараға","Иш-чарага")}</Link><h1 className="text-2xl font-bold">{tr("Заявки, группы и квалификация","Өтінімдер, топтар және іріктеу","Өтүнмөлөр, топтор жана квалификация")}</h1><h2>{data?.event.title}</h2><select aria-label="Session" disabled={busy} value={sessionId} onChange={e=>void load(e.target.value).catch(err=>setMessage(err.message))}>{sessions.map(s=><option key={s.id} value={s.id}>{new Date(s.start_time).toLocaleString("ru-RU",{timeZone:"Europe/Moscow"})} МСК</option>)}</select>{message&&<p role="status" className="rounded-lg border border-cyan-700/30 p-3">{message}</p>}
 {data?.published?<p>{tr("Результаты опубликованы. Исключение участника с перерасчётом выполняет администратор в редакторе результатов.","Нәтижелер жарияланған. Қатысушыны алып тастауды әкімші нәтижелер редакторында орындайды.","Жыйынтыктар жарыяланган. Катышуучуну алып салууну администратор жыйынтык редакторунда аткарат.")} <Link className="text-cyan-300" href={`/tournaments/${eventId}/manage-results?sessionId=${sessionId}`}>{tr("Открыть результаты","Нәтижелерді ашу","Жыйынтыктарды ачуу")}</Link></p>:<>
 {started&&<label className="block rounded-lg border border-amber-600/40 p-3"><input type="checkbox" checked={confirmStarted} onChange={e=>setConfirmStarted(e.target.checked)}/> {tr("Подтверждаю изменение заявки начавшегося этапа. Сыгранные составы и результаты сохраняются.","Басталған кезең өтінімін өзгертуді растаймын. Ойналған құрамдар мен нәтижелер сақталады.","Башталган этаптын өтүнмөсүн өзгөртүүнү ырастайм. Ойнолгон курамдар жана жыйынтыктар сакталат.")}</label>}
 <section className="cyber-card space-y-3 p-4"><h2 className="font-bold">{editing?tr("Изменить заявку","Өтінімді өзгерту","Өтүнмөнү өзгөртүү"):tr("Добавить участника","Қатысушы қосу","Катышуучу кошуу")}</h2>{!editing&&<div className="flex flex-wrap gap-2"><select aria-label="Participant type" value={targetType} onChange={e=>{setTargetType(e.target.value as typeof targetType);setCandidates([]);setTarget(null);}}><option value="team">{tr("Организация","Ұйым","Уюм")}</option><option value="player">{tr("Игрок","Ойыншы","Оюнчу")}</option></select><input aria-label="Search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={tr("Название или ник","Атауы немесе ник","Аталышы же ник")}/><button className="secondary-button" disabled={busy} onClick={()=>void search()}>{tr("Найти","Іздеу","Издөө")}</button></div>}{!editing&&candidates.map(item=><button key={item.id} className="mr-2 text-cyan-300" onClick={()=>void choose(item,targetType)}>{item.name??item.nickname}</button>)}{target&&<div className="space-y-3"><p className="font-bold">{target.name??target.nickname}</p><div className="grid gap-2 sm:grid-cols-3">{players.map(p=><label key={p.id}><input type="checkbox" checked={roster.includes(p.id)} onChange={e=>setRoster(ids=>e.target.checked?[...ids,p.id]:ids.filter(id=>id!==p.id))}/> {p.nickname} · {p.game_id}</label>)}</div><select aria-label="Group" value={groupId} onChange={e=>setGroupId(e.target.value)}><option value="">{tr("Свободная группа","Бос топ","Бош топ")}</option>{data?.groups.map(g=><option key={g.id} value={g.id}>{g.public_number}. {g.name}</option>)}</select><select aria-label="Status" value={status} onChange={e=>setStatus(e.target.value)}><option value="confirmed">{tr("Подтверждён","Расталған","Ырасталган")}</option><option value="waiting">{tr("Ожидание","Күту","Күтүү")}</option></select><button className="primary-button" disabled={busy||started&&!confirmStarted} onClick={()=>void act({action:editing?"edit":"add",id:editing??undefined,targetId:target.id,targetType,roster,groupId:groupId||null,status})}>{tr("Сохранить заявку","Өтінімді сақтау","Өтүнмөнү сактоо")}</button>{editing&&<button className="secondary-button" onClick={()=>{setEditing(null);setTarget(null);}}>{tr("Отмена","Бас тарту","Жокко чыгаруу")}</button>}</div>}</section>
 {data?.role!=="responsible"&&<div className="flex flex-wrap gap-2">{(["random","balanced"] as const).map(mode=><button key={mode} className="secondary-button" disabled={busy||started&&!confirmStarted} onClick={()=>void act({action:"distribute",mode})}>{mode==="random"?tr("Распределить случайно","Кездейсоқ бөлу","Кокус бөлүштүрүү"):tr("Распределить по силе составов","Құрам күшіне қарай бөлу","Курам күчүнө жараша бөлүштүрүү")}</button>)}</div>}
 </>}
 <section className="space-y-2"><label className="block">{tr("Поиск среди заявок","Өтінімдерден іздеу","Өтүнмөлөрдөн издөө")}<input className="ml-2" value={registrationQuery} onChange={e=>{setRegistrationQuery(e.target.value);setVisibleCount(50);}}/></label><p>{registrations.length}</p>{registrations.slice(0,visibleCount).map(r=><article key={r.id} className="cyber-card space-y-2 p-3"><div className="flex flex-wrap justify-between gap-2"><Link className="font-bold text-cyan-300" href={r.team_id?`/teams/${r.team_id}`:`/profile/${r.participant_user_id}`}>{r.name_snapshot??r.team_id??r.participant_user_id}</Link><span>{tr("Группа","Топ","Топ")} {data?.groups.find(g=>g.id===r.group_id)?.public_number??"—"} · {r.status==="waiting"?tr("Ожидание","Күту","Күтүү"):tr("Подтверждён","Расталған","Ырасталган")}</span></div><p>{(r.roster_snapshot??[]).map((p,i)=><span key={p.id}>{i>0&&", "}<Link href={`/profile/${p.id}`}>{p.nickname}</Link></span>)}</p>{Number(r.carried_points)!==0&&<p>{tr("Перенесённые очки","Көшірілген ұпайлар","Көчүрүлгөн упайлар")}: {r.carried_points}</p>}{!data?.published&&<div className="flex gap-3"><button disabled={busy} className="text-cyan-300" onClick={()=>{const kind=r.team_id?"team":"player";setEditing(r.id);setTargetType(kind);setGroupId(r.group_id??"");setStatus(r.status);void choose({id:r.team_id??r.participant_user_id!,name:r.name_snapshot??""},kind,r.roster_json);}}>{tr("Изменить","Өзгерту","Өзгөртүү")}</button><button disabled={busy||started&&!confirmStarted} className="text-red-300" onClick={()=>void act({action:"remove",id:r.id})}>{tr("Исключить","Шығару","Чыгаруу")}</button></div>}</article>)}{registrations.length>visibleCount&&<button className="secondary-button" onClick={()=>setVisibleCount(n=>n+50)}>{tr("Показать ещё","Тағы көрсету","Дагы көрсөтүү")}</button>}</section>
 {data?.source&&data.role!=="responsible"&&<section className="cyber-card space-y-3 p-4"><h2 className="font-bold">{tr("Прошедшие квалификацию","Іріктеуден өткендер","Квалификациядан өткөндөр")}</h2>{data.qualification?.needs_review&&<p className="text-amber-200">{tr("Результаты квалификации изменились или ещё не подтверждены. Проверьте список.","Іріктеу нәтижелері өзгерген немесе расталмаған. Тізімді тексеріңіз.","Квалификациянын жыйынтыктары өзгөргөн же ырастала элек. Тизмени текшериңиз.")}</p>}{started&&<p>{tr("Этап уже начался. Его состав автоматически не меняется; расхождение сохранено для организатора.","Кезең басталған. Құрамы автоматты өзгермейді; айырмашылық ұйымдастырушыға көрсетіледі.","Этап башталган. Курам автоматтык өзгөрбөйт; айырма уюштуруучуга көрсөтүлөт.")}</p>}<button className="secondary-button" disabled={started||data.published} onClick={()=>setSelectedIds((data.qualification?.suggested??[]).map(s=>s.registrationId))}>{tr("Выбрать по правилам квалификации","Іріктеу ережелері бойынша таңдау","Квалификация эрежелери боюнча тандоо")}</button><label className="block">{tr("Поиск участника","Қатысушыны іздеу","Катышуучуну издөө")}<input className="ml-2" value={qualificationQuery} onChange={e=>{setQualificationQuery(e.target.value);setQualificationCount(50);}}/></label><p>{tr("Выбрано","Таңдалған","Тандалган")}: {selectedIds.length}</p>{qualifiers.slice(0,qualificationCount).map(s=><label key={s.registrationId} className="block"><input disabled={started||data.published} type="checkbox" checked={selectedIds.includes(s.registrationId)} onChange={e=>setSelectedIds(ids=>e.target.checked?[...ids,s.registrationId]:ids.filter(id=>id!==s.registrationId))}/> {s.place}. {s.name} · {s.points}</label>)}{qualifiers.length>qualificationCount&&<button className="secondary-button" onClick={()=>setQualificationCount(n=>n+50)}>{tr("Показать ещё","Тағы көрсету","Дагы көрсөтүү")}</button>}<button className="primary-button" disabled={busy||started||data.published} onClick={()=>void act({action:"qualify",sourceRevision:data.source!.revision,selectedIds})}>{tr("Подтвердить состав следующего этапа","Келесі кезең құрамын растау","Кийинки этаптын курамын ырастоо")}</button></section>}
 </main>;
}
