"use client";
import {useState} from "react";
import {authFetch} from "@/utils/api/auth-fetch";
import {useLanguage} from "./LanguageProvider";
import {competitionText} from "@/i18n/competition";
import type {CompetitionContext,ResultInput} from "@/lib/competition/model";
import type {ImportMapping,UnresolvedImport} from "@/lib/competition/import";
interface Proposed {rows:ResultInput[];unresolved:UnresolvedImport[];report:string[]}
export default function ResultsImport({eventId,apiBase,sessionId,publicId,context,disabled,onApply}:{eventId:string;apiBase?:string;sessionId:string;publicId:string;context:CompetitionContext;disabled:boolean;onApply:(rows:ResultInput[])=>void}){
 const {locale}=useLanguage();const t=(key:Parameters<typeof competitionText>[1])=>competitionText(locale,key);const tr=(ru:string,kk:string,ky:string)=>locale==="kk"?kk:locale==="ky"?ky:ru;
 const [file,setFile]=useState<File|null>(null),[result,setResult]=useState<Proposed|null>(null),[mappings,setMappings]=useState<Record<string,ImportMapping>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const base=`${apiBase??`/api/admin/events/${eventId}/competition-results`}/import`;
 const parse=async(source:File,map:Record<string,ImportMapping>)=>{setBusy(true);setMessage("");try{const form=new FormData();form.set("file",source);form.set("sessionId",sessionId);form.set("mappings",JSON.stringify(map));const r=await authFetch(base,{method:"POST",body:form}),data=await r.json();if(!r.ok)throw new Error(data.error);setResult(data);}catch(e){setMessage(e instanceof Error?e.message:t("failed"));}finally{setBusy(false);}};
 const mappingChange=(line:number,patch:ImportMapping)=>setMappings(m=>({...m,[line]:{...m[line],...patch}}));
 return <section className="cyber-card space-y-4 p-4"><h2 className="font-bold">{t("import")}</h2><button className="text-cyan-300" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await authFetch(`${base}?sessionId=${sessionId}`);if(!r.ok)throw new Error((await r.json()).error);const url=URL.createObjectURL(await r.blob()),a=document.createElement("a");a.href=url;a.download=`${publicId}.xlsx`;a.click();URL.revokeObjectURL(url);}catch(e){setMessage(e instanceof Error?e.message:t("failed"));}finally{setBusy(false);}}}>{t("download")}</button><label className="block">XLSX / CSV / JSON<input className="ml-3" type="file" accept=".xlsx,.csv,.json" disabled={disabled||busy} onChange={e=>{const f=e.target.files?.[0];if(f){setFile(f);setMappings({});setResult(null);void parse(f,{});}}}/></label>{message&&<p role="alert">{message}</p>}
 {result&&<div className="space-y-3"><p>{result.report.join(" ")}</p>{result.unresolved?.map(row=>{const mapping=mappings[String(row.line)]??{},entrants=mapping.registrationId?context.entrants.filter(e=>e.id===mapping.registrationId):context.entrants;return <div key={row.line} className="space-y-2 rounded-lg border border-amber-400/30 p-3"><p>#{row.line}: {Object.values(row.record).filter(Boolean).join(" · ")}</p><p className="text-amber-200">{row.reason}</p><div className="flex flex-wrap gap-3"><label>{t("target")}<select value={mapping.registrationId??""} onChange={e=>mappingChange(row.line,{registrationId:e.target.value||undefined,gameId:undefined,userId:undefined})}><option value="">{t("choose")}</option>{context.entrants.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>{t("game")}<select value={mapping.gameId??""} onChange={e=>mappingChange(row.line,{gameId:e.target.value||undefined})}><option value="">{t("choose")}</option>{context.games.filter(g=>entrants.some(e=>e.groupId===g.groupId)).map(g=><option key={g.id} value={g.id}>{g.publicId} · {g.map}</option>)}</select></label><label>{t("player")}<select value={mapping.guest?"guest":mapping.userId??""} onChange={e=>mappingChange(row.line,{userId:e.target.value&&e.target.value!=="guest"?e.target.value:undefined,guest:e.target.value==="guest"})}><option value="">{t("teamOnly")}</option><option value="guest">{t("guest")}</option>{entrants.flatMap(e=>e.roster.map(p=><option key={`${e.id}:${p.id}`} value={p.id}>{e.name}: {p.nickname} · {p.gameId}</option>))}</select></label><label><input type="checkbox" checked={!!mapping.skip} onChange={e=>mappingChange(row.line,{skip:e.target.checked})}/>{tr("Пропустить строку","Жолды өткізу","Сапты өткөрүү")}</label></div></div>;})}
 <div className="flex flex-wrap gap-3">{!!result.unresolved?.length&&<button className="secondary-button" disabled={busy||disabled} onClick={()=>file&&void parse(file,mappings)}>{tr("Применить сопоставления","Сәйкестіктерді қолдану","Шайкештиктерди колдонуу")}</button>}<button className="primary-button" disabled={busy||disabled||!!result.unresolved?.length} onClick={()=>{onApply(result.rows);setResult(null);setMessage(tr("Черновик заменён. Проверьте все игры перед публикацией.","Жоба ауыстырылды. Жариялау алдында барлық ойынды тексеріңіз.","Долбоор алмаштырылды. Жарыялоо алдында бардык оюнду текшериңиз."));}}>{tr("Заменить черновик импортом","Жобаны импортпен ауыстыру","Долбоорду импорт менен алмаштыруу")}</button><button className="secondary-button" onClick={()=>setResult(null)}>{t("cancel")}</button></div></div>}</section>;
}
