"use client";
import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {authFetch} from "@/utils/api/auth-fetch";
import {useLanguage} from "./LanguageProvider";
import {competitionText} from "@/i18n/competition";
interface Group{id:string;number:number;name:string;capacity:number;publicId:string;canViewRoom:boolean;code?:string;password?:string;note?:string}
interface Data{description:string;canManage:boolean;canCloseComments:boolean;commentsClosed:boolean;commentsOpen:boolean;groups:Group[]}
export default function SessionControls({eventId,sessionId,authenticated}:{eventId:string;sessionId:string;authenticated:boolean}){
 const {locale}=useLanguage();const t=(key:Parameters<typeof competitionText>[1])=>competitionText(locale,key),tr=(ru:string,kk:string,ky:string)=>locale==="kk"?kk:locale==="ky"?ky:ru;
 const [data,setData]=useState<Data|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const endpoint=`/api/events/${eventId}/session-control`;
 const load=useCallback(async()=>{try{const r=await(authenticated?authFetch:fetch)(`${endpoint}?sessionId=${sessionId}`),d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);}catch(e){setMessage(e instanceof Error?e.message:"Ошибка");}},[authenticated,endpoint,sessionId]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
 const save=async(patch:Record<string,unknown>)=>{setBusy(true);try{const r=await authFetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId,...patch})}),d=await r.json();if(!r.ok)throw new Error(d.error);setMessage(tr("Сохранено","Сақталды","Сакталды"));if(patch.action==="comments")window.dispatchEvent(new Event("competition-comments-changed"));await load();}catch(e){setMessage(e instanceof Error?e.message:t("failed"));}finally{setBusy(false);}};
 if(!data)return message?<p role="status">{message}</p>:null;
 return <div className="my-4 space-y-3">{message&&<p role="status">{message}</p>}{data.canManage?<form className="space-y-2" onSubmit={e=>{e.preventDefault();void save({action:"description",description:new FormData(e.currentTarget).get("description")});}}><label className="block">{tr("Описание сессии","Сессия сипаттамасы","Сессия сүрөттөмөсү")}<textarea key={data.description} className="mt-1 w-full rounded-lg bg-slate-950 p-3" maxLength={10000} name="description" defaultValue={data.description}/></label><button className="secondary-button" disabled={busy}>{tr("Сохранить описание","Сипаттаманы сақтау","Сүрөттөмөнү сактоо")}</button></form>:data.description&&<p className="whitespace-pre-wrap">{data.description}</p>}
 <div className="grid gap-3 sm:grid-cols-2">{data.groups.map(g=><article className="rounded-xl border border-cyan-900/40 bg-slate-950/40 p-3" key={g.id}><h3 className="font-bold">{t("group")} {g.number} · {g.name}</h3><p className="text-xs text-white/50">{g.publicId} · {g.capacity}</p>{g.canViewRoom&&(data.canManage?<form key={`${g.code}:${g.password}:${g.note}`} className="mt-3 space-y-2" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save({action:"room",groupId:g.id,code:f.get("code"),password:f.get("password"),note:f.get("note")});}}><label className="block">{tr("Комната","Бөлме","Бөлмө")}<input className="w-full rounded-lg bg-slate-950 p-2" name="code" defaultValue={g.code} maxLength={100}/></label><label className="block">{tr("Пароль","Құпиясөз","Сырсөз")}<input className="w-full rounded-lg bg-slate-950 p-2" name="password" defaultValue={g.password} maxLength={100}/></label><textarea aria-label={tr("Примечание","Ескерту","Эскертме")} className="w-full rounded-lg bg-slate-950 p-2" name="note" defaultValue={g.note} maxLength={2000}/><button disabled={busy} className="secondary-button">{tr("Сохранить комнату","Бөлмені сақтау","Бөлмөнү сактоо")}</button></form>:<div className="mt-3"><p>{tr("Комната","Бөлме","Бөлмө")}: {g.code||"—"}</p><p>{tr("Пароль","Құпиясөз","Сырсөз")}: {g.password||"—"}</p><p className="whitespace-pre-wrap">{g.note}</p></div>)}</article>)}</div>
 {data.canManage&&<Link className="secondary-button inline-flex" href={`/tournaments/${eventId}/participants?sessionId=${sessionId}`}>{tr("Заявки, группы и квалификация","Өтінімдер, топтар және іріктеу","Өтүнмөлөр, топтор жана квалификация")}</Link>}
 {data.canCloseComments&&<button className="secondary-button" disabled={busy} onClick={()=>void save({action:"comments",closed:!data.commentsClosed})}>{data.commentsClosed?tr("Открыть обсуждение в пределах срока","Талқылауды мерзім ішінде ашу","Талкууну мөөнөт ичинде ачуу"):tr("Закрыть обсуждение сессии","Сессия талқылауын жабу","Сессия талкуусун жабуу")}</button>}</div>;
}
